version: '3.7'

services:
    img_processor:
        build: .
        volumes:
            - ./src:/app/src
            - ./input:/app/input
            - ./output:/app/output
        command:
            python3 /app/src/img_process.py --verbose
